<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="6" total="14" passed="2" failed="6" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-06T15:37:14 IST" name="Xalts-Assignment" finished-at="2024-11-06T15:37:56 IST" duration-ms="41794">
    <groups>
    </groups>
    <test started-at="2024-11-06T15:37:14 IST" name="Tests" finished-at="2024-11-06T15:37:56 IST" duration-ms="41794">
      <class name="com.xalts.tst.assignment_xalts_TestCases.SignOutTest">
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:com.xalts.tst.assignment_xalts_TestCases.SignOutTest@2ddc9a9f]" started-at="2024-11-06T15:37:51 IST" name="setUp" finished-at="2024-11-06T15:37:54 IST" duration-ms="3245" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="signOutTest(java.lang.String,java.lang.String)[pri:0, instance:com.xalts.tst.assignment_xalts_TestCases.SignOutTest@2ddc9a9f]" started-at="2024-11-06T15:37:54 IST" name="signOutTest" data-provider="signOutData" finished-at="2024-11-06T15:37:56 IST" duration-ms="1896" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Komiri.raja95890@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Raja$1234]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Test failed due to an exception: unexpected alert open: {Alert text : User not found}
  (Session info: chrome=130.0.6723.92): User not found
Build info: version: '4.25.0', revision: '8a8aea2337'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.10'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [45d306f9d96499e5c70c26c6b7bd4321, findElement {value=//button[normalize-space()='Sign Out'], using=xpath}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 130.0.6723.92, chrome: {chromedriverVersion: 130.0.6723.93 (dbcf0550c05e..., userDataDir: C:\Users\RAJAKS~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:64120}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:64120/devtoo..., se:cdpVersion: 130.0.6723.92, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 45d306f9d96499e5c70c26c6b7bd4321]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Test failed due to an exception: unexpected alert open: {Alert text : User not found}
  (Session info: chrome=130.0.6723.92): User not found
Build info: version: '4.25.0', revision: '8a8aea2337'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.10'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [45d306f9d96499e5c70c26c6b7bd4321, findElement {value=//button[normalize-space()='Sign Out'], using=xpath}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 130.0.6723.92, chrome: {chromedriverVersion: 130.0.6723.93 (dbcf0550c05e..., userDataDir: C:\Users\RAJAKS~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:64120}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:64120/devtoo..., se:cdpVersion: 130.0.6723.92, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 45d306f9d96499e5c70c26c6b7bd4321
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.xalts.tst.assignment_xalts_TestCases.SignOutTest.signOutTest(SignOutTest.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signOutTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.xalts.tst.assignment_xalts_TestCases.SignOutTest@2ddc9a9f]" started-at="2024-11-06T15:37:56 IST" name="tearDown" finished-at="2024-11-06T15:37:56 IST" duration-ms="197" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.xalts.tst.assignment_xalts_TestCases.SignOutTest -->
      <class name="com.xalts.tst.assignment_xalts_TestCases.SignInTest">
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:com.xalts.tst.assignment_xalts_TestCases.SignInTest@2e385cce]" started-at="2024-11-06T15:37:37 IST" name="setUp" finished-at="2024-11-06T15:37:44 IST" duration-ms="6458" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="signInTest(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.xalts.tst.assignment_xalts_TestCases.SignInTest@2e385cce]" started-at="2024-11-06T15:37:44 IST" name="signInTest" data-provider="signInData" finished-at="2024-11-06T15:37:46 IST" duration-ms="2224" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Komiri.raja9589034@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Raja$1235]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[positive]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Test failed due to an exception: unexpected alert open: {Alert text : User not found}
  (Session info: chrome=130.0.6723.92): User not found
Build info: version: '4.25.0', revision: '8a8aea2337'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.10'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [d2786d5cdf8662e1423d1c1451417282, findElement {value=//button[normalize-space()='Sign Out'], using=xpath}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 130.0.6723.92, chrome: {chromedriverVersion: 130.0.6723.93 (dbcf0550c05e..., userDataDir: C:\Users\RAJAKS~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:64059}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:64059/devtoo..., se:cdpVersion: 130.0.6723.92, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: d2786d5cdf8662e1423d1c1451417282]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Test failed due to an exception: unexpected alert open: {Alert text : User not found}
  (Session info: chrome=130.0.6723.92): User not found
Build info: version: '4.25.0', revision: '8a8aea2337'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.10'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [d2786d5cdf8662e1423d1c1451417282, findElement {value=//button[normalize-space()='Sign Out'], using=xpath}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 130.0.6723.92, chrome: {chromedriverVersion: 130.0.6723.93 (dbcf0550c05e..., userDataDir: C:\Users\RAJAKS~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:64059}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:64059/devtoo..., se:cdpVersion: 130.0.6723.92, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: d2786d5cdf8662e1423d1c1451417282
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.xalts.tst.assignment_xalts_TestCases.SignInTest.signInTest(SignInTest.java:80)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signInTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.xalts.tst.assignment_xalts_TestCases.SignInTest@2e385cce]" started-at="2024-11-06T15:37:46 IST" name="tearDown" finished-at="2024-11-06T15:37:46 IST" duration-ms="176" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:com.xalts.tst.assignment_xalts_TestCases.SignInTest@2e385cce]" started-at="2024-11-06T15:37:46 IST" name="setUp" finished-at="2024-11-06T15:37:49 IST" duration-ms="2840" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="signInTest(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.xalts.tst.assignment_xalts_TestCases.SignInTest@2e385cce]" started-at="2024-11-06T15:37:49 IST" name="signInTest" data-provider="signInData" finished-at="2024-11-06T15:37:50 IST" duration-ms="789" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Komiri.raja9589034@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Tests@123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[negative]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Test failed due to an exception: unexpected alert open: {Alert text : User not found}
  (Session info: chrome=130.0.6723.92): User not found
Build info: version: '4.25.0', revision: '8a8aea2337'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.10'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [d2786d5cdf8662e1423d1c1451417282, findElement {value=//button[normalize-space()='Sign Out'], using=xpath}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 130.0.6723.92, chrome: {chromedriverVersion: 130.0.6723.93 (dbcf0550c05e..., userDataDir: C:\Users\RAJAKS~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:64059}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:64059/devtoo..., se:cdpVersion: 130.0.6723.92, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: d2786d5cdf8662e1423d1c1451417282,
'Sign In' button should be disabled for invalid credentials. expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Test failed due to an exception: unexpected alert open: {Alert text : User not found}
  (Session info: chrome=130.0.6723.92): User not found
Build info: version: '4.25.0', revision: '8a8aea2337'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.10'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [d2786d5cdf8662e1423d1c1451417282, findElement {value=//button[normalize-space()='Sign Out'], using=xpath}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 130.0.6723.92, chrome: {chromedriverVersion: 130.0.6723.93 (dbcf0550c05e..., userDataDir: C:\Users\RAJAKS~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:64059}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:64059/devtoo..., se:cdpVersion: 130.0.6723.92, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: d2786d5cdf8662e1423d1c1451417282,
'Sign In' button should be disabled for invalid credentials. expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.xalts.tst.assignment_xalts_TestCases.SignInTest.signInTest(SignInTest.java:80)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signInTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.xalts.tst.assignment_xalts_TestCases.SignInTest@2e385cce]" started-at="2024-11-06T15:37:50 IST" name="tearDown" finished-at="2024-11-06T15:37:51 IST" duration-ms="352" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.xalts.tst.assignment_xalts_TestCases.SignInTest -->
      <class name="com.xalts.tst.assignment_xalts_TestCases.SignUpTest">
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:com.xalts.tst.assignment_xalts_TestCases.SignUpTest@3e27aa33]" started-at="2024-11-06T15:37:19 IST" name="setUp" finished-at="2024-11-06T15:37:22 IST" duration-ms="3280" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="signUpTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.xalts.tst.assignment_xalts_TestCases.SignUpTest@3e27aa33]" started-at="2024-11-06T15:37:22 IST" name="signUpTest" data-provider="signUpData" finished-at="2024-11-06T15:37:23 IST" duration-ms="1119" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Komiri.raja95890@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Raja$1234]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Raja$1234]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[positive]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.xalts.tst.assignment_xalts_TestCases.SignUpTest@3e27aa33]" started-at="2024-11-06T15:37:23 IST" name="tearDown" finished-at="2024-11-06T15:37:24 IST" duration-ms="288" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:com.xalts.tst.assignment_xalts_TestCases.SignUpTest@3e27aa33]" started-at="2024-11-06T15:37:24 IST" name="setUp" finished-at="2024-11-06T15:37:27 IST" duration-ms="3663" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="signUpTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.xalts.tst.assignment_xalts_TestCases.SignUpTest@3e27aa33]" started-at="2024-11-06T15:37:27 IST" name="signUpTest" data-provider="signUpData" finished-at="2024-11-06T15:37:28 IST" duration-ms="792" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Komiri.raja95890@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Raja$1235]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Raja$1235]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[negative]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Sign Up button should be disabled for invalid credentials. expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Sign Up button should be disabled for invalid credentials. expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.xalts.tst.assignment_xalts_TestCases.SignUpTest.signUpTest(SignUpTest.java:65)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.xalts.tst.assignment_xalts_TestCases.SignUpTest@3e27aa33]" started-at="2024-11-06T15:37:28 IST" name="tearDown" finished-at="2024-11-06T15:37:29 IST" duration-ms="337" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:com.xalts.tst.assignment_xalts_TestCases.SignUpTest@3e27aa33]" started-at="2024-11-06T15:37:29 IST" name="setUp" finished-at="2024-11-06T15:37:32 IST" duration-ms="3279" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="signUpTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.xalts.tst.assignment_xalts_TestCases.SignUpTest@3e27aa33]" started-at="2024-11-06T15:37:32 IST" name="signUpTest" data-provider="signUpData" finished-at="2024-11-06T15:37:33 IST" duration-ms="797" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[komiriraja]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Tests@123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Tests@123]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[negative]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Sign Up button should be disabled for invalid credentials. expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Sign Up button should be disabled for invalid credentials. expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.xalts.tst.assignment_xalts_TestCases.SignUpTest.signUpTest(SignUpTest.java:65)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.xalts.tst.assignment_xalts_TestCases.SignUpTest@3e27aa33]" started-at="2024-11-06T15:37:33 IST" name="tearDown" finished-at="2024-11-06T15:37:33 IST" duration-ms="238" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:com.xalts.tst.assignment_xalts_TestCases.SignUpTest@3e27aa33]" started-at="2024-11-06T15:37:33 IST" name="setUp" finished-at="2024-11-06T15:37:36 IST" duration-ms="2985" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="signUpTest(java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:com.xalts.tst.assignment_xalts_TestCases.SignUpTest@3e27aa33]" started-at="2024-11-06T15:37:36 IST" name="signUpTest" data-provider="signUpData" finished-at="2024-11-06T15:37:37 IST" duration-ms="614" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Sign Up button should be disabled for invalid credentials. expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Sign Up button should be disabled for invalid credentials. expected [false] but found [true]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.xalts.tst.assignment_xalts_TestCases.SignUpTest.signUpTest(SignUpTest.java:65)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUpTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.xalts.tst.assignment_xalts_TestCases.SignUpTest@3e27aa33]" started-at="2024-11-06T15:37:37 IST" name="tearDown" finished-at="2024-11-06T15:37:37 IST" duration-ms="242" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.xalts.tst.assignment_xalts_TestCases.SignUpTest -->
      <class name="com.xalts.tst.assignment_xalts_TestCases.HomePageTest">
        <test-method is-config="true" signature="loadConfig()[pri:0, instance:com.xalts.tst.assignment_xalts_TestCases.HomePageTest@6574a52c]" started-at="2024-11-06T15:37:14 IST" name="loadConfig" finished-at="2024-11-06T15:37:14 IST" duration-ms="150" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadConfig -->
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:com.xalts.tst.assignment_xalts_TestCases.HomePageTest@6574a52c]" started-at="2024-11-06T15:37:14 IST" name="setUp" finished-at="2024-11-06T15:37:18 IST" duration-ms="3706" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="homePageTest()[pri:0, instance:com.xalts.tst.assignment_xalts_TestCases.HomePageTest@6574a52c]" started-at="2024-11-06T15:37:18 IST" name="homePageTest" finished-at="2024-11-06T15:37:18 IST" duration-ms="123" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- homePageTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.xalts.tst.assignment_xalts_TestCases.HomePageTest@6574a52c]" started-at="2024-11-06T15:37:18 IST" name="tearDown" finished-at="2024-11-06T15:37:18 IST" duration-ms="218" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:com.xalts.tst.assignment_xalts_TestCases.HomePageTest@6574a52c]" started-at="2024-11-06T15:37:56 IST" name="afterSuite" finished-at="2024-11-06T15:37:56 IST" duration-ms="261" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.xalts.tst.assignment_xalts_TestCases.HomePageTest -->
    </test> <!-- Tests -->
  </suite> <!-- Xalts-Assignment -->
</testng-results>
